version: '3.7'

services:
    db:
      image: postgres:9.6-alpine
      ports:
        - '5432:5432'
      environment:
        POSTGRES_USER: 'daegon'
        POSTGRES_PASSWORD: '0000'
        POSTGRES_DB: 'atlantiqueDiveSite'
      volumes:
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
        
    api:
      image: php
      build: ./atlantiqueDiveApi
      ports:
        - '8000:8000'
      depends_on: 
        - db



# for launch the container use the command below
# sudo docker-compose -f docker-compose.yml up
