version: '3.3'

services:
    www:
      container_name: nginx
      image: nginx:alpine
      build:
         context: .
         dockerfile: Dockerfile
      ports:
        - "80:80"
      depends_on:
        - backend
        - frontend
    db:
      container_name: mariadb
      image: mariadb
      container_name: db
      restart: unless-stopped
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '0000'
        MYSQL_USER: 'daegon'
        MYSQL_PASSWORD: '0000'
        MYSQL_DATABASE: 'atlantiqueDiveSite'
      volumes:
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
        
    backend:
      container_name: laravel
      image: php:7.4-fpm
      build:
        args:
          user: daegon
          uid: 1000
        context: ./atlantiqueDiveApi
        dockerfile: Dockerfile
      depends_on: 
        - db

    frontend:
      container_name: vue
      image: node
      build:
        args:
          user: daegon
          uid: 1000
        context: ./frontend
        dockerfile: Dockerfile

# for launch the container use the command below
# docker-compose up --build
