version: '3.7'

services:
    www:
      image: nginx:alpine
      build:
         context: .
         dockerfile: Dockerfile
      # volumes:
      #   - '/etc/nginx/conf.d/default.conf'
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend
        - frontend
        
    db:
      image: mariadb
      container_name: db
      restart: unless-stopped
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '0000'
        MYSQL_USER: 'daegon'
        MYSQL_PASSWORD: '0000'
        MYSQL_DATABASE: 'atlantiqueDiveSite'
      volumes:
        - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
        
    backend:
      image: php:7.4-fpm
      build:
        args:
          user: daegon
          uid: 1000
        context: ./atlantiqueDiveApi
        dockerfile: Dockerfile
      depends_on: 
        - db
    
    # frontend:
    #   image: node:lts-alpine
    #   build: ./frontend
    #   ports:
    #     - '8080:8080'
    #   depends_on: 
    #     - backend

    frontend:
      image: node:current-alpine
      working_dir: /home/node/app
      volumes:
      - ./frontend:/home/node/app
      environment:
        NODE_ENV: development
      command: "npm run serve"




# for launch the container use the command below
# sudo docker-compose -f docker-compose.yml up
