FROM php:7.4-fpm

ARG user
ARG uid

USER root
# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
# RUN useradd -G www-data,root -u $uid -d /home/$user $user
# RUN mkdir -p /home/$user/.composer && \
#     chown -R $user:$user /home/$user

RUN mkdir -p /backend

ADD . /backend/

WORKDIR /backend

COPY .env.example /backend/.env

# RUN chown -R $user:$user /backend


# USER $user

RUN composer install

RUN php artisan config:cache

RUN php artisan key:generate

RUN php artisan storage:link

CMD php artisan serve --host=0.0.0.0 --port=8000
